
const $=id=>document.getElementById(id),id=new URLSearchParams(location.search).get("id");let detail=null;
async function load(){if(!id){$("pageMsg").textContent="Missing session ID.";return}const {data,error}=await JBE.client.rpc("teacher_session_detail",{p_session_id:id});if(error){$("pageMsg").textContent=error.message;return}detail=data;render()}
function render(){
 const s=detail.session;$("sessionSummary").innerHTML=`<h2>${s.course_title}</h2><p class="ops-muted">${s.group_name||""} • ${new Date(s.session_date).toLocaleString()}</p><p>${JBE_I18N.t("Planned")}: ${s.planned_duration_minutes||"—"} min ${s.actual_duration_minutes?`• ${JBE_I18N.t("Duration")}: ${s.actual_duration_minutes} min`:""}</p>`;
 $("startBtn").disabled=!!s.actual_start_at;$("endBtn").disabled=!!s.billing_finalized;
 $("roster").innerHTML=(detail.students||[]).map(st=>`<div class="ops-item"><div class="ops-item-main"><strong>${st.full_name_en||st.full_name}</strong><small>${st.student_code}</small></div><div class="ops-toolbar"><select id="status-${st.student_id}"><option value="present">${JBE_I18N.t("present")}</option><option value="late">${JBE_I18N.t("late")}</option><option value="absent">${JBE_I18N.t("absent")}</option><option value="excused">${JBE_I18N.t("excused")}</option></select><input id="min-${st.student_id}" type="number" min="0" value="${s.actual_duration_minutes||s.planned_duration_minutes||0}" style="width:90px"><input id="note-${st.student_id}" placeholder="Note" style="min-width:150px"><button class="ops-btn small" onclick="saveAttendance('${st.student_id}')">${JBE_I18N.t("Save Attendance")}</button></div></div>`).join("")||`<p class="ops-muted">—</p>`;
 $("activities").innerHTML=(detail.activities||[]).map(a=>`<div class="ops-item"><div><strong>${a.title}</strong><small>${JBE_I18N.t(a.activity_type)} ${a.due_at?`• ${new Date(a.due_at).toLocaleString()}`:""}</small></div></div>`).join("");
 JBE_I18N.apply();
}
$("startBtn").onclick=async()=>{const {error}=await JBE.client.rpc("teacher_start_session",{p_session_id:id});$("sessionMsg").textContent=error?error.message:JBE_I18N.t("Session started");if(!error)load()};
$("endBtn").onclick=async()=>{if(!confirm("End this session and finalize billing rules?"))return;const {data,error}=await JBE.client.rpc("teacher_end_session",{p_session_id:id});$("sessionMsg").textContent=error?error.message:`${JBE_I18N.t("Session ended")} • ${data?.minutes??""} min`;if(!error)load()};
window.saveAttendance=async sid=>{const {error}=await JBE.client.rpc("teacher_record_session_attendance",{p_session_id:id,p_student_id:sid,p_status:$(`status-${sid}`).value,p_minutes:Number($(`min-${sid}`).value||0),p_note:$(`note-${sid}`).value||""});if(error)alert(error.message);else alert(JBE_I18N.t("Attendance saved"))};
$("homeworkForm").onsubmit=async e=>{e.preventDefault();const due=$("hwDue").value?new Date($("hwDue").value).toISOString():null;const {error}=await JBE.client.rpc("teacher_add_homework",{p_session_id:id,p_title:$("hwTitle").value,p_description:$("hwDesc").value||"",p_due_at:due,p_resource_url:$("hwUrl").value||""});$("hwMsg").textContent=error?error.message:JBE_I18N.t("Homework published");if(!error){e.target.reset();load()}};
window.addEventListener("jbe:languagechange",render);load();
